/**
 * Check-in ids are generated by the client, so POST /checkins is an upsert.
 *
 * Two properties have to hold together: a retried create must land on the same
 * row rather than duplicating it, and that must not become a way to write to
 * another account's row. The upsert targets (userId, id) for exactly that
 * reason — the bare primary key is not userId-scoped.
 *
 * Runs against the real SQLite file on throwaway users and cleans up after
 * itself.
 */
import { prisma } from '../../lib/prisma';
import { createCheckIn } from '../checkins.service';
import type { CheckInInput } from '../../schemas/checkin.schema';

const input = (over: Partial<CheckInInput> = {}): CheckInInput => ({
  weightKg: 70,
  sources: {
    weight: 'manual',
    height: 'manual',
    sleep: 'manual',
    steps: 'manual',
    water: 'manual',
  },
  recordedAt: '2026-09-01T08:00:00.000Z',
  ...over,
});

const makeUser = () =>
  prisma.user.create({
    data: {
      email: `identity-${Date.now()}-${Math.random()}@test.local`,
      passwordHash: 'x',
    },
  });

let userId: string;

// Ids are client-chosen now, so a bare literal would collide with the same
// literal in another suite — Jest runs them in parallel against one SQLite file.
// Namespacing by the throwaway user keeps each run's ids to itself.
const ck = (name: string) => `${userId}_${name}`;

beforeEach(async () => {
  userId = (await makeUser()).id;
});

afterEach(async () => {
  await prisma.checkIn.deleteMany({ where: { userId } });
  await prisma.user.delete({ where: { id: userId } });
});

afterAll(async () => {
  await prisma.$disconnect();
});

const rowCount = () => prisma.checkIn.count({ where: { userId } });

describe('createCheckIn identity', () => {
  it('keeps the id the client chose', async () => {
    const row = await createCheckIn(userId, input({ id: ck('chosen') }));
    expect(row.id).toBe(ck('chosen'));
  });

  it('assigns one when the client sends none', async () => {
    const row = await createCheckIn(userId, input());
    expect(row.id).toEqual(expect.any(String));
    expect(row.id).not.toBe('');
  });

  it('does not duplicate when a create is retried', async () => {
    // The offline case: the row landed but the response was lost, so the client
    // sends the identical request again.
    const first = await createCheckIn(userId, input({ id: ck('1'), weightKg: 70 }));
    const second = await createCheckIn(userId, input({ id: ck('1'), weightKg: 70 }));

    expect(second.id).toBe(first.id);
    expect(await rowCount()).toBe(1);
  });

  it('applies the newer body when a retry carries an edit', async () => {
    await createCheckIn(userId, input({ id: ck('1'), weightKg: 70 }));
    const updated = await createCheckIn(userId, input({ id: ck('1'), weightKg: 72 }));

    expect(updated.weightKg).toBe(72);
    expect(await rowCount()).toBe(1);
  });

  it('lets two accounts keep separate rows without interfering', async () => {
    await createCheckIn(userId, input({ id: ck('mine'), weightKg: 70 }));

    const other = await makeUser();
    await createCheckIn(other.id, input({ id: ck('theirs'), weightKg: 90 }));

    expect(await rowCount()).toBe(1);
    expect(await prisma.checkIn.count({ where: { userId: other.id } })).toBe(1);

    await prisma.checkIn.deleteMany({ where: { userId: other.id } });
    await prisma.user.delete({ where: { id: other.id } });
  });

  it('refuses to write to an id another account already owns', async () => {
    // The upsert finds no (otherUser, ck('mine')) row, tries to create one, and
    // hits the primary key. It must surface as a conflict rather than silently
    // overwriting — and the owner's data must be untouched.
    await createCheckIn(userId, input({ id: ck('mine'), weightKg: 70 }));

    const other = await makeUser();
    await expect(
      createCheckIn(other.id, input({ id: ck('mine'), weightKg: 999 })),
    ).rejects.toMatchObject({ code: 'P2002' });

    const mine = await prisma.checkIn.findUnique({ where: { id: ck('mine') } });
    expect(mine?.weightKg).toBe(70);
    expect(mine?.userId).toBe(userId);

    await prisma.user.delete({ where: { id: other.id } });
  });
});
